version: '3.4'

services:
  sqldata:
    image: "postgres"
    ports: 
      - "5432:5432"
    env_file:
      - sqldata.env
    volumes:
      - ./gateway_schema.sql:/docker-entrypoint-initdb.d/gateway_schema.sql

  nosqldata:
    image: mongo
    ports: 
      - "27017:27017"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  paymentgateway:
    image: ${DOCKER_REGISTRY-}paymentgateway
    build:
      context: .
      dockerfile: PaymentGateway/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
      - nosqldata

  banksimulator:
    image: ${DOCKER_REGISTRY-}banksimulator
    build:
      context: .
      dockerfile: BankSimulator/Dockerfile

  paymentgatewayworker:
    image: ${DOCKER_REGISTRY-}paymentgatewayworker
    build:
      context: .
      dockerfile: PaymentGatewayWorker/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
      - nosqldata
      - banksimulator

